const cats = [
    {
        id: 0,
        type: "cat",
        breed: "Ragdoll",
        age: 5,
        good_with_cats: "Yes",
        good_with_dogs: "Yes",
        temperament: ["Intelligent", "Friendly", "Affectionate", "Inquisitive"],
        good_with_kids: "Yes",
        good_with_elderly: "Yes",
        good_with_strangers: "Yes",
        independent: "Yes",
        hypoallergenic: "Yes",
        health_status: "Healthy",
        house_cat: "Yes"
    }, 
    {
        id: 1,
        type: "cat",
        breed: "Devon Rex",
        age: 6,
        good_with_cats: "No",
        good_with_dogs: "No",
        temperament: ["Sociable", "Affectionate", "Energetic", "Lively"],
        good_with_kids: "Yes",
        good_with_elderly: "Yes",
        good_with_strangers: "No",
        independent: "No",
        hypoallergenic: "Yes",
        health_status: "Healthy",
        house_cat: "No"
    },
    {
        id: 2,
        type: "cat",
        breed: "Sphynx",
        age: 3,
        good_with_cats: "Yes",
        good_with_dogs: "No",
        temperament: ["Intelligent", "Sociable", "Energetic", "Lively"],
        good_with_kids: "No",
        good_with_elderly: "No",
        good_with_strangers: "No",
        independent: "Yes",
        hypoallergenic: "Yes",
        health_status: "Healthy",
        house_cat: "No"
    }, 
    {
        id: 3,
        type: "cat",
        breed: "Scottish Fold",
        age: 10,
        good_with_cats: "Yes",
        good_with_dogs: "No",
        temperament: "",
        good_with_kids: "Yes",
        good_with_elderly: "Yes",
        good_with_strangers: "Yes",
        independent: "No",
        hypoallergenic: "No",
        health_status: "Healthy",
        house_cat: "Yes"
    }, 
    {
        id: 4,
        type: "cat",
        breed: "Main Coon",
        age: 8,
        good_with_cats: "No",
        good_with_dogs: "Yes",
        temperament: ["Active", "Curious", "Lively"],
        good_with_kids: "No",
        good_with_elderly: "Yes",
        good_with_strangers: "No",
        independent: "Yes",
        hypoallergenic: "No",
        health_status: "Yes",
        house_cat: "No"
    }, 
    {
        id: 5,
        type: "cat",
        breed: "Persian",
        age: 7,
        good_with_cats: "Yes",
        good_with_dogs: "Yes",
        temperament: ["Loyal", "Affectionate"],
        good_with_kids: "No",
        good_with_elderly: "No",
        good_with_strangers: "No",
        independent: "Yes",
        hypoallergenic: "No",
        health_status: "Diabetic",
        house_cat: "Yes"
    }, 
    {
        id: 6,
        type: "cat",
        breed: "Burmese",
        age: 12,
        good_with_cats: "Yes",
        good_with_dogs: "No",
        temperament: ["Active", "Curious", "Lively"],
        good_with_kids: "Yes",
        good_with_elderly: "No",
        good_with_strangers: "No",
        independent: "Yes",
        hypoallergenic: "Yes",
        health_status: "Healthy",
        house_cat: "No"
    }, 
    {
        id: 7,
        type: "cat",
        breed: "Cymric",
        age: 6,
        good_with_cats: "No",
        good_with_dogs: "No",
        temperament: ["Playful", "Loyal", "Friendly", "Affectionate"],
        good_with_kids: "Yes",
        good_with_elderly: "Yes",
        good_with_strangers: "Yes",
        independent: "No",
        hypoallergenic: "Yes",
        health_status: "Healthy",
        house_cat: "Yes"
    }, 
    {
        id: 8,
        type: "cat",
        breed: "Colorpoint Shorthair",
        age: 13,
        good_with_cats: "No",
        good_with_dogs: "No",
        temperament: ["Social", "Affectionate", "Intelligent", "Playful"],
        good_with_kids: "No",
        good_with_elderly: "No",
        good_with_strangers: "No",
        independent: "Yes",
        hypoallergenic: "Yes",
        health_status: "Healthy",
        house_cat: "No"
    }, 
    {
        id: 9,
        type: "cat",
        breed: "Bombay",
        age: 9,
        good_with_cats: "Yes",
        good_with_dogs: "No",
        temperament: ["Active", "Intelligent", "Playful", "Curious"],
        good_with_kids: "Yes",
        good_with_elderly: "Yes",
        good_with_strangers: "Yes",
        independent: "No",
        hypoallergenic: "No",
        health_status: "Healthy",
        house_cat: "Yes"
    }, 
    {
        id: 10,
        type: "cat",
        breed: "Norwegian Forest Cat",
        age: 12,
        good_with_cats: "Yes",
        good_with_dogs: "Yes",
        temperament: ["Active", "Intelligent", "Playful", "Curious"],
        good_with_kids: "Yes",
        good_with_elderly: "Yes",
        good_with_strangers: "Yes",
        independent: "No",
        hypoallergenic: 'No',
        health_status: "Gingivitis",
        house_cat: "Yes"
    }

]

