const cats = [
    {
        id: 0,
        type: "cat",
        breed: "Ragdoll",
        age: 5,
        good_with_cats: true,
        good_with_dogs: true,
        temperament: ["Intelligent", "Friendly", "Affectionate", "Inquisitive"],
        good_with_kids: true,
        good_with_elderly: true,
        good_with_strangers: true,
        independent: true,
        hypoallergenic: true,
        health_status: "Healthy",
        house_cat: true
    }, 
    {
        id: 1,
        type: "cat",
        breed: "Devon Rex",
        age: 6,
        good_with_cats: false,
        good_with_dogs: false,
        temperament: ["Sociable", "Affectionate", "Energetic", "Lively"],
        good_with_kids: true,
        good_with_elderly: true,
        good_with_strangers: false,
        independent: false,
        hypoallergenic: true,
        health_status: "Healthy",
        house_cat: false
    },
    {
        id: 2,
        type: "cat",
        breed: "Sphynx",
        age: 3,
        good_with_cats: true,
        good_with_dogs: false,
        temperament: ["Intelligent", "Sociable", "Energetic", "Lively"],
        good_with_kids: false,
        good_with_elderly: false,
        good_with_strangers: false,
        independent: true,
        hypoallergenic: true,
        health_status: "Healthy",
        house_cat: false
    }, 
    {
        id: 3,
        type: "cat",
        breed: "Scottish Fold",
        age: 10,
        good_with_cats: true,
        good_with_dogs: false,
        temperament: ["Intelligent", "Curious", "Sociable", "Affectionate"],
        good_with_kids: true,
        good_with_elderly: true,
        good_with_strangers: true,
        independent: false,
        hypoallergenic: false,
        health_status: "Healthy",
        house_cat: true
    }, 
    {
        id: 4,
        type: "cat",
        breed: "Main Coon",
        age: 8,
        good_with_cats: false,
        good_with_dogs: true,
        temperament: ["Active", "Curious", "Lively"],
        good_with_kids: false,
        good_with_elderly: true,
        good_with_strangers: false,
        independent: true,
        hypoallergenic: false,
        health_status: true,
        house_cat: false
    }, 
    {
        id: 5,
        type: "cat",
        breed: "Persian",
        age: 7,
        good_with_cats: true,
        good_with_dogs: true,
        temperament: ["Loyal", "Affectionate"],
        good_with_kids: false,
        good_with_elderly: false,
        good_with_strangers: false,
        independent: true,
        hypoallergenic: false,
        health_status: "Diabetic",
        house_cat: true
    }, 
    {
        id: 6,
        type: "cat",
        breed: "Burmese",
        age: 12,
        good_with_cats: true,
        good_with_dogs: false,
        temperament: ["Active", "Curious", "Lively"],
        good_with_kids: true,
        good_with_elderly: false,
        good_with_strangers: false,
        independent: true,
        hypoallergenic: true,
        health_status: "Healthy",
        house_cat: false
    }, 
    {
        id: 7,
        type: "cat",
        breed: "Cymric",
        age: 6,
        good_with_cats: false,
        good_with_dogs: false,
        temperament: ["Playful", "Loyal", "Friendly", "Affectionate"],
        good_with_kids: true,
        good_with_elderly: true,
        good_with_strangers: true,
        independent: false,
        hypoallergenic: true,
        health_status: "Healthy",
        house_cat: true
    }, 
    {
        id: 8,
        type: "cat",
        breed: "Colorpoint Shorthair",
        age: 13,
        good_with_cats: false,
        good_with_dogs: false,
        temperament: ["Social", "Affectionate", "Intelligent", "Playful"],
        good_with_kids: false,
        good_with_elderly: false,
        good_with_strangers: false,
        independent: true,
        hypoallergenic: true,
        health_status: "Healthy",
        house_cat: false
    }, 
    {
        id: 9,
        type: "cat",
        breed: "Bombay",
        age: 9,
        good_with_cats: true,
        good_with_dogs: false,
        temperament: ["Active", "Intelligent", "Playful", "Curious"],
        good_with_kids: true,
        good_with_elderly: true,
        good_with_strangers: true,
        independent: false,
        hypoallergenic: false,
        health_status: "Healthy",
        house_cat: true
    }, 
    {
        id: 10,
        type: "cat",
        breed: "Norwegian Forest Cat",
        age: 12,
        good_with_cats: true,
        good_with_dogs: true,
        temperament: ["Active", "Intelligent", "Playful", "Curious"],
        good_with_kids: true,
        good_with_elderly: true,
        good_with_strangers: true,
        independent: false,
        hypoallergenic: 'No',
        health_status: "Gingivitis",
        house_cat: true
    }

]

module.exports = cats;
